server:
  port: 8765

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){cyan} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){magenta}%n"
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinition: INFO

eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  config:
    import:
      - "optional:configserver:"

  output:
    ansi:
      enabled: DETECT

  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: test_route
          uri: http://httpbin.org:80/
          predicates:
            - Path=/get
          filters:
            - AddRequestHeader=MyHeader, MyUri
            - AddRequestHeader=MyParam, MyValue

        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/products,/products/**
